### ISSUE TITLE
Getting error: sounddevice.PortAudioError: Error querying device -1

### ISSUE THREAD

**Issue by ithjz** [googlesamples/assistant-sdk-python#113]
assistant-sdk-python-master/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 399, in <module>
    main()
  File "E:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "E:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:/Documents/Tencent Files/1437352232/FileRecv/assistant-sdk-python-master/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 371, in main
    flush_size=audio_flush_size)
  File "D:/Documents/Tencent Files/1437352232/FileRecv/assistant-sdk-python-master/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 187, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "E:\ProgramData\Anaconda3\lib\site-packages\sounddevice.py", line 1521, in __init__
    **_remove_self(locals()))
  File "E:\ProgramData\Anaconda3\lib\site-packages\sounddevice.py", line 948, in __init__
    samplerate)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sounddevice.py", line 2746, in _get_stream_parameters
    info = query_devices(device)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sounddevice.py", line 755, in query_devices
    raise PortAudioError('Error querying device {0}'.format(device))
sounddevice.PortAudioError: Error querying device -1

Process finished with exit code 1

**Comment by Fleker** [comment]
`sounddevice.PortAudioError: Error querying device -1`
Seems like your device is unable to find a speaker or microphone

**Comment by Fleker** [comment]
Are you still seeing issues? If so, we can re-open this issue.

**Comment by nikhilsuvarna89** [comment]
still facing this problem
`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 411, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 383, in main
    flush_size=audio_flush_size)
  File "/usr/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/usr/lib/python3.7/site-packages/sounddevice.py", line 1264, in __init__
    **_remove_self(locals()))
  File "/usr/lib/python3.7/site-packages/sounddevice.py", line 780, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/usr/lib/python3.7/site-packages/sounddevice.py", line 2572, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]`

**Comment by nikhilsuvarna89** [comment]
> Are you still seeing issues? If so, we can re-open this issue.
**is this issue resolved?**
`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 411, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 383, in main
    flush_size=audio_flush_size)
  File "/usr/lib/python3.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/usr/lib/python3.7/site-packages/sounddevice.py", line 1264, in __init__
    **_remove_self(locals()))
  File "/usr/lib/python3.7/site-packages/sounddevice.py", line 780, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/usr/lib/python3.7/site-packages/sounddevice.py", line 2572, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]`

**Comment by kalyaniakant** [comment]
I am getting the error as
PortAudioError: Error querying device -1
