### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by malikasinger1** [googlesamples/assistant-sdk-python#120]
tried with admin privilage
tried to google and stackoverflow
tried both `pip install google-assistant-sdk` and `pip install --upgrade google-assistant-sdk`
on win 10 latest updated
python 3.6.2 anaconda 3 installed

cmd screen here:
```
C:\Users\AdMin>pip install --upgrade google-assistant-sdk
Collecting google-assistant-sdk
Exception:
Traceback (most recent call last):
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\AdMin\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

C:\Users\AdMin>
C:\Users\AdMin>
```

**Comment by teganburns** [comment]
http://bfy.tw/EdVv "conda install --force html5lib" should fix the problem.
https://github.com/python-mechanize/mechanize/issues/6

**Comment by malikasinger1** [comment]
thanks, it worked
