### ISSUE TITLE
Authorization tool

### ISSUE THREAD

**Issue by saifabuhashish** [googlesamples/assistant-sdk-python#125]
I am trying to build the googe assistant SDK on a linux busybox. I have gotten to the point where I need use the authorization tool to authorize the google assistant SDK to make google assitant queries. When I run the following command:
google-oauthlib-tool --client-secrets /path/to/client_secret_client-id.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless

I get the following error:
Traceback (most recent call last):
  File "/home/root/projects/seti/exe/env/bin/google-oauthlib-tool", line 11, in <module>
    sys.exit(main())
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/click/_unicodefun.py", line 64, in _verify_python3_env
    stderr=subprocess.PIPE).communicate()[0]
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'locale'
(env) root@k2g-evm:~# FileNotFoundError: [Errno 2] No such file or directory: 'locale'

Any ideas how I can solve this issue?

**Comment by proppy** [comment]
It seems that click require the `locale` command to be present https://github.com/pallets/click/blob/950463bd15f877c1163d40b59238b10c637d5b3e/click/_unicodefun.py#L65 in order to check for unicode support.

Did you include locale and unicode support in your busybox build?

Alternatively if you only need to generate the credentials, you can just copy the file generated by the tool (you can configure it with the `--credentials` option) on your target system.

**Comment by saifabuhashish** [comment]
Thank you. I am confused by which file you're referring to though? when running the tool, I get the error I referred to above, it doesn't generate any file...

**Comment by proppy** [comment]
@saifabuhashish the error message is referring to the `locale` tool, a [standard](http://man7.org/linux/man-pages/man1/locale.1.html) tool present in most linux distribution.

**Comment by saifabuhashish** [comment]
I understand that. By tool I was referring to the authorization tool that you mentioned above:
" you can just copy the file generated by the tool (you can configure it with the --credentials option) on your target system."
When I run the authorization tool, I get the locale error. Is there anyway else I can get the credentials file?

**Comment by proppy** [comment]
@saifabuhashish oh sorry, I was referring to the `google-oauthlib-tool` tool.

I'd suggest to run the tool first on a system that has the `locale` binary, and the copy the generated file to your target device.

**Comment by saifabuhashish** [comment]
I just did that, copied the entire .config directory to my target system, which contains the credentials file, I am getting the following error:
Traceback (most recent call last):
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/auth/transport/requests.py", line 112, in __call__
    **kwargs)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root/projects/seti/exe/env/bin/google-assistant-demo", line 11, in <module>
    sys.exit(main())
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/assistant/__main__.py", line 66, in main
    with Assistant(credentials) as assistant:
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/assistant/library/assistant.py", line 93, in __init__
    credentials, self._set_credentials)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/assistant/library/auth_helpers.py", line 40, in __init__
    self._credentials.refresh(http_request)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/oauth2/credentials.py", line 117, in refresh
    self._client_secret))
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/oauth2/_client.py", line 189, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/oauth2/_client.py", line 104, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/google/auth/transport/requests.py", line 115, in __call__
    raise exceptions.TransportError(exc)
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))


I apologize for the long post, but this is the entire error message that I get.

**Comment by proppy** [comment]
@saifabuhashish seems like you're missing `ca-certificates` on your target device.
https://packages.debian.org/search?keywords=ca-certificates

**Comment by saifabuhashish** [comment]
@proppy Thanks for the quick replies. My problem is thta the Linux environment that I'm working with is just a Linux kernel v4.4.41, so theres no real OS on my target device, so I dont think these debian ca-certificate packages would be compatible with the system that I'm working with... any other suggestions?

**Comment by proppy** [comment]
@saifabuhashish if you `strace` the process you should be able to find the location that are being tried for  certs file and copy them from the debian package to this location.

**Comment by Fleker** [comment]
Are you still seeing this issue? If so, we can re-open this issue.

**Comment by AbhishekPande99** [comment]
I'm having the same problem
