### ISSUE TITLE
Getting segmentation fault and audio crash when running from stock Raspbian

### ISSUE THREAD

**Issue by jrgleason** [googlesamples/assistant-sdk-python#127]
I am trying to get the AIY kit up without the Google supplied image. I have followed the steps in the HACKING.md file, however, when I start the service I see...

```
pi@raspberrypi:~/code/voice-recognizer-raspi $ source env/bin/activate(env) pi@raspberrypi:~/code/voice-recognizer-raspi $ python3 src/assistant_library_demo.py
ALSA lib pcm.c:8403:(snd_pcm_set_params) Rate doesn't match (requested 16000Hz, get 48000Hz)
[1215:1253:ERROR:audio_input_processor.cc(755)] Input error
Say "OK, Google" then speak, or press Ctrl+C to quit...
Segmentation fault
``` 

I am using the stock AIY kit. Also when I try to run `make` I get...

```
(env) pi@raspberrypi:~/code/voice-recognizer-raspi $ make
PYTHONPATH=$PWD/src python3 -m unittest discover tests
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.5/unittest/main.py", line 117, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.5/unittest/loader.py", line 338, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: 'tests'
Makefile:6: recipe for target 'check' failed
make: *** [check] Error 1
```

**Comment by jrgleason** [comment]
Also when I run alsa_info I see `'/sys/module/snd_soc_googlevoicehat_soundcard/parameters/*': No such file or directory`

**Comment by shivasiddharth** [comment]
If you open the asoundrc, you can see that the raspbian would have populated it with a audio config on its own. Either clear that or copy paste the contents of asound.conf into asoundrc. You should be good to go..

**Comment by jrgleason** [comment]
@shivasiddharth yeah I had a hard time deciding where to open it thanks!
