### ISSUE TITLE
Unauthenticated?

### ISSUE THREAD

**Issue by jesperandersson89** [googlesamples/assistant-sdk-python#138]
Hi!
I have been following this guide: https://developers.google.com/assistant/sdk/develop/grpc/
And everything was going great until I actually tried to use "googlesamples-assistant-pushtotalk".
(found here: https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk)
I have made sure everything on the "Activity Controls page" is as it should, and I can see failed attempts to connect from my computer on my API dashboard. 
Do you have any tips or suggestions for solving this one?
Thanks!
```
C:\Users\Mediadator>google-oauthlib-tool --client-secrets C:\Heidi\client_secret
_425569872344-ah7ohkh6hb8s02rii.apps.googleusercontent.com.json --scope 
https://www.googleapis.com/auth/assistant-sdk-prototype --save

Please visit this URL to authorize this application: https://accounts.google.com
/o/oauth2/auth?response_type=code&client_id=425569872344-ah7ohvkh6hb8s07882
f3o452rii.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%
2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&state
=0ZV85EvczQG862ZQde1lSeVe&access_type=offline

credentials saved: C:\Users\Mediadator\AppData\Roaming\google-oauthlib-tool\credentials.json

C:\Users\Mediadator>pip install --upgrade google-assistant-sdk[samples]
Requirement already up-to-date: google-assistant-sdk[samp..... (abv.)
..............................
Installing collected packages: urllib3
  Found existing installation: urllib3 1.22
    Uninstalling urllib3-1.22:
      Successfully uninstalled urllib3-1.22
Successfully installed urllib3-1.21.1

C:\Users\Mediadator>googlesamples-assistant-pushtotalk
AsioDrv::: CAsioDrv()...
AsioDrv::: InitWdmDrv()...
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
Traceback (most recent call last):
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in 
_run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in 
_run_code
    exec(code, run_globals)
  File "C:\Users\Mediadator\AppData\Local\Programs\Python\Python36-32\Scripts\googlesamples-
assistant-pushtotalk.exe\__main__.py", line 9, in <module>
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\googlesamples\assistant\grpc\pushtotalk.py", line 317, in main
    continue_conversation = assistant.converse()
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\tenacity\__init__.py", line 87, in wrapped_f
    return r.call(f, *args, **kw)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\tenacity\__init__.py", line 235, in call
    do = self.iter(result=result, exc_info=exc_info)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\tenacity\__init__.py", line 194, in iter
    return fut.result()
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\concurrent
\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\concurrent
\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\tenacity\__init__.py", line 238, in call
    result = fn(*args, **kwargs)
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\googlesamples\assistant\grpc\pushtotalk.py", line 110, in converse
    self.deadline):
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\grpc\_channel.py", line 348, in __next__
    return self._next()
  File "c:\users\mediadator\appdata\local\programs\python\python36-32\lib\site-packages
\grpc\_channel.py", line 342, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, 
Request is missing required authentication credential. Expected OAuth 2 access token, 
login cookie or other valid authentication credential. 
See https://developers.google.com/identity/sign-in/web/devconsole-project.)>
```

**Comment by mtaylor-create** [comment]
I actually had everything working just fine... it's been giving me no trouble for the past few weeks and just today it seems to have un-authenticated itself and now gives me the same message it's giving you.  It may or may not be related... wish I could be of some help though.

**Comment by Fleker** [comment]
Looks similar to
https://github.com/googlesamples/assistant-sdk-cpp/issues/12#issuecomment-349841929

**Comment by project-owner** [comment]
Same here. To reproduce just run one of your examples - pushtotalk.py. It's not working anymore.

**Comment by Fleker** [comment]
Yes we became aware of this issue last night and are rolling out a fix. Thanks for reporting.

**Comment by Fleker** [comment]
The fix should be fully rolled out now.

**Comment by mtaylor-create** [comment]
Confirmed working!  Thank you for the prompt resolution!

**Comment by megnia** [comment]
It's working, Thank you!

**Comment by Ranjith1992** [comment]
It's working, Thank you!

**Comment by Taconut** [comment]
The issue started happening again for me. Anyone else in the same boat? It was working for a while though, which is nice.

**Comment by Fleker** [comment]
@Taconut what error are you getting? It seems to work fine for my test case.

**Comment by Taconut** [comment]
It started working a few minutes before you posted and it's been working ever since... I'll post on here if it stops again.

**Comment by ritik17** [comment]
@Fleker Can you please help me with this issue .
GoogleAdsException: (<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential.
