### ISSUE TITLE
PortAudioError(errormsg, err) sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]

### ISSUE THREAD

**Issue by JawsOrca** [googlesamples/assistant-sdk-python#155]
Hi All,

Sorry stupid beginner questions.

I'm trying this project on a Raspberry Pi 3.

I have a cheap usb webcam with a mic and a usbpowered mic driven speakers.

I'm entering: python -m googlesamples.assistant.grpc.pushtotalk

And I keep getting an error:

(env) pi@raspberrypi:~ $ python -m googlesamples.assistant.grpc.pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 434, in <module>
    main()
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 332, in main
    flush_size=audio_flush_size
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 187, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in __init__
    **_remove_self(locals()))
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 772, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
    **raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]**

(env) pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

.asoundrc =

pcm.!default {
        type hw
        card 0
}

ctl.!default {
        type hw
        card 0
}

If I do the speaker test I hear the test.

If I test record this works too.

Sorry I've tried several suggestions from stackoverflow etc but nothings working and I'm getting a bit lost. I'm starting to suspect that the webcam just isn't compatible with this project but hope you guys can help before I give up!

Thanks in advance, p.s I'm a right novice with the pi and linux :(

**Comment by moham96** [comment]
I have a similar problem

> (env) ➜  ~ python -m googlesamples.assistant.grpc.pushtotalk
> INFO:root:Connecting to embeddedassistant.googleapis.com
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 435, in <module>
>     main()
>   File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 332, in main
>     flush_size=audio_flush_size
>   File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 187, in __init__
>     blocksize=int(block_size/2),  # blocksize is in number of frames.
>   File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in __init__
>     **_remove_self(locals()))
>   File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 673, in __init__
>     samplerate)
>   File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2481, in _get_stream_parameters
>     info = query_devices(device)
>   File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 480, in query_devices
>     raise PortAudioError('Error querying device {0}'.format(device))
> sounddevice.PortAudioError: Error querying device -1
 
can this be fixed using some configurations ?

**Comment by Fleker** [comment]
The asoundrc doesn't seem to be in the right format https://developers.google.com/assistant/sdk/guides/library/python/embed/audio

**Comment by shivasiddharth** [comment]
@Fleker ,  Even with a properly configured .asoundrc and asound.conf, there seems to be this Portaudio problem and its only with the gRPC API. This occurs if you give a delayed speech input or speech input quickly after triggering. Please find below as to what happens and when.

1. Trigger the assistant and immediately provide a speech input.
Portaudio Error.

2. Trigger the assistant and wait for a second before providing speech input.
No Portaudio error and GA works fine.

3. Trigger the assistant wait for a couple of seconds and provide a speech input.
Portaudio error.

4. Trigger the assistant and dont give any speech input.
Nothing happens and assistant times out as it should.

This issue occurs even with the provided pushtotalk (unmodified and using enter key as trigger).

Thanks.

**Comment by karrarmaher** [comment]
I have the same problem @Fleker any updates on this ?

**Comment by proppy** [comment]
@JawsOrca @karrarmaher @shivasiddharth @moham96 can you give a try to #188 ?

**Comment by moham96** [comment]
@proppy I got the pushtotalk sample to work once but I wasn't able to replicate the results.and after I deleted my env and tried to install the packages again I got import errors as outlined in #189

**Comment by bimbim2401** [comment]
Hello, i am using a raspberry with a just boom amp hat connecting together and an usb mic, i have my proper asound.conf which looks like this : 

pcm.dsnooper {
type dsnoop
ipc_key 816357492
ipc_key_add_uid 0
ipc_perm 0666
slave {
pcm "hw:1,0"
channels 1
}
}

pcm.!default {
type asym
playback.pcm {
type plug
slave.pcm "hw:0,0"
}
capture.pcm {
type plug
slave.pcm "dsnooper"
}
}

And i have install a python script made by  shivasiddharth for an google assistant , the "ok google" is working great but the pushbutton.py ( https://github.com/shivasiddharth/GassistPi/blob/master/src/pushbutton.py) returns this log ( i have change the pin indicated in the file with another one as it uses by the amp hat). Can you please help me, i have create an issue on the git project but no solution for the moment to resolve the bug https://github.com/shivasiddharth/GassistPi/issues/356

i see in the fix https://github.com/googlesamples/assistant-sdk-python/pull/188 some precisions but do not know how to implemented this fix in this project or maybe it s a format problem of the asound file or with the mic...

2018-05-26 12:04:59,739 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-05-26 12:04:59,748 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com
2018-05-26 12:04:59,999 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-05-26 12:05:00,049 INFO root Connecting to embeddedassistant.googleapis.com
2018-05-26 12:05:01,132 ERROR main Error opening RawStream: Device unavailable [PaErrorCode -9985]
Traceback (most recent call last):
File "/home/pi/GassistPi/src/pushbutton.py", line 804, in
main()
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/home/pi/GassistPi/src/pushbutton.py", line 681, in main
flush_size=audio_flush_size
File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in init
blocksize=int(block_size/2), # blocksize is in number of frames.
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in init
**_remove_self(locals()))
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 772, in init
'Error opening {0}'.format(self.class.name))
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]
2018-05-26 12:05:09,089 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-05-26 12:05:09,099 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com
2018-05-26 12:05:09,341 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-05-26 12:05:09,369 INFO root Connecting to embeddedassistant.googleapis.com
2018-05-26 12:05:10,451 ERROR main Error opening RawStream: Device unavailable [PaErrorCode -9985]
Traceback (most recent call last):
File "/home/pi/GassistPi/src/pushbutton.py", line 804, in
main()
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/home/pi/GassistPi/src/pushbutton.py", line 681, in main
flush_size=audio_flush_size
File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in init
blocksize=int(block_size/2), # blocksize is in number of frames.
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in init
**_remove_self(locals()))
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 772, in init
'Error opening {0}'.format(self.class.name))
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]
2018-05-26 12:05:18,500 DEBUG google.auth.transport.requests Making request: POST https://accounts.google.com/o/oauth2/token
2018-05-26 12:05:18,513 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): accounts.google.com
2018-05-26 12:05:18,772 DEBUG urllib3.connectionpool https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-05-26 12:05:18,800 INFO root Connecting to embeddedassistant.googleapis.com
2018-05-26 12:05:19,891 ERROR main Error opening RawStream: Device unavailable [PaErrorCode -9985]
Traceback (most recent call last):
File "/home/pi/GassistPi/src/pushbutton.py", line 804, in
main()
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/home/pi/GassistPi/src/pushbutton.py", line 681, in main
flush_size=audio_flush_size
File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in init
blocksize=int(block_size/2), # blocksize is in number of frames.
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in init
**_remove_self(locals()))
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 772, in init
'Error opening {0}'.format(self.class.name))
File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]

**Comment by Fleker** [comment]
Are you still seeing this issue? If so, we can re-open this issue.

**Comment by karrarmaher** [comment]
https://github.com/shivasiddharth

Here is a complete project

**Comment by bibipkins** [comment]
same issue for me

**Comment by AndroiDjo** [comment]
I have same issue. Making project by https://developers.google.com/assistant/sdk/guides/service/python/

**Comment by yashatgit** [comment]
I was having the same issue and was able to solve by adding `rate` field in my config. It is something like this:
```
pcm.speaker {
  type plug
  slave {
    pcm “hw:0,0”
    rate 16000
  }
}
```

**Comment by VBota1** [comment]
Hello,

To fix the issue with the sample rate on my ubuntu server I had to modify my `.asoundrc` file like this:

```
pcm.!default {
     type asym
     playback.pcm {
             type plug
             slave.pcm "hw:0,0"
     }
     capture.pcm {
             type plug
             slave.pcm "hw:0,0"
     } 
}
```

now it works.

**Comment by yeunbok2g** [comment]
just add "rate 16000" for output like below

pcm.!default {
type asym
capture.pcm "input"
playback.pcm "output"
}
pcm.input {
type plug
slave {
pcm "hw:1,0"
}
}
pcm.output {
type plug
slave {
pcm "hw:0,0"
> **rate 16000**
}
}
