### ISSUE TITLE
JSONDecodeError 

### ISSUE THREAD

**Issue by JulianMined** [googlesamples/assistant-sdk-python#156]
I'm using the hotword example (German)

> ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'schalte das Licht heller'}
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/lib/python3.5/dist-packages/google/assistant/library/assistant.py", line 134, in __call__
    args = json.loads(event_bytes.decode(encoding='UTF-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ON_RESPONDING_STARTED:
  {'is_error_response': False}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

**Comment by Fleker** [comment]
So you wanted to turn up the brightness of a light? Are you trying to turn up the brightness of the device running the hotword example?

Can you try to give an absolute brightness, ie. "set the brightness to 80"?

**Comment by JulianMined** [comment]
Yes, thats right.

I can set absolute brightness without a problem

**Comment by Fleker** [comment]
Can you edit the hotword sample to print out the JSON output? I imagine it's a Device action, but I don't know what it would be sending.

Relative changes do not work as there's no flow to obtain the current brightness (like a Smart Home [QUERY](https://developers.google.com/actions/smarthome/#report-state) intent)

**Comment by JulianMined** [comment]
I cannot print the JSON, it looks like a internal problem.
