### ISSUE TITLE
typo in variable causes crash

### ISSUE THREAD

**Issue by kadeve** [googlesamples/assistant-sdk-python#16]
https://github.com/googlesamples/assistant-sdk-python/blob/master/googlesamples/assistant/__main__.py#L119

should be 
`resp.result.spoken_response_text`
 i think

**Comment by animeshp** [comment]
Yeah. I also think so.

Getting the following traceback

> Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.py", line 320, in <module>
    main()
  File "/home/pi/env/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.py", line 313, in main
    continue_conversation = assistant.converse()
  File "/home/pi/env/lib/python3.4/site-packages/tenacity/__init__.py", line 87, in wrapped_f
    return r.call(f, *args, **kw)
  File "/home/pi/env/lib/python3.4/site-packages/tenacity/__init__.py", line 235, in call
    do = self.iter(result=result, exc_info=exc_info)
  File "/home/pi/env/lib/python3.4/site-packages/tenacity/__init__.py", line 194, in iter
    return fut.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/home/pi/env/lib/python3.4/site-packages/tenacity/__init__.py", line 238, in call
    result = fn(*args, **kwargs)
  File "/home/pi/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.py", line 119, in converse
    resp.result.spnoken_response_text)
AttributeError: 'ConverseResult' object has no attribute 'spnoken_response_text'

**Comment by proppy** [comment]
Yep, should be fixed with #17 and #20
