### ISSUE TITLE
google-assistant-demo doesn't work 

### ISSUE THREAD

**Issue by harry0890** [googlesamples/assistant-sdk-python#180]
Q: I run google-assistant-demo fail because of  "ctypes _dlopen can not open this library "/venv/lib/python3.4/site-packages/google/assistant/library/**libassistant_embedder.so**".

Note:
- This "libassistant_embedder.so" comes from "pip install -v google-assistant-library==1.0.1"
- My platform is 32bit ARMv7 linux, not Raspberry Pi2 or 3.

How can I solve this issue? 

```
(venv) root@OpenWrt:/venv/bin# google-assistant-demo --credentials /venv/credentials.json  --device_model_id gapi_123-my-model-identifier --project_id decisive-force-185

Traceback (most recent call last):
  File "/venv/bin/google-assistant-demo", line 11, in <module>
    sys.exit(main())
  File "/venv/lib/python3.4/site-packages/google/assistant/__main__.py", line 66, in main
    with Assistant(credentials) as assistant:
  File "/venv/lib/python3.4/site-packages/google/assistant/library/assistant.py", line 87, in __init__
    self._load_lib()
  File "/venv/lib/python3.4/site-packages/google/assistant/library/assistant.py", line 202, in _load_lib
    self._lib = cdll.LoadLibrary(lib_path)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 431, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 352, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: File not found
```

**Comment by Fleker** [comment]
Did you pip install ctypes?

**Comment by harry0890** [comment]
Hi Fleker,
Yes, I already have installed ctypes. I can see dynamic library by cpython3.4 in this location. 
`/usr/lib/python3.4/lib-dynload/_ctypes.cpython-34.so`
and the ctypes path:
# /usr/lib/python3.4/ctypes/
# ls
__init__.py  _endian.py   macholib     test         util.py      wintypes.py


- Origninal, the source code try to dlopen libassistant_embedder.so
```
&gt;&gt;&gt; from _ctypes import dlopen as _dlopen
&gt;&gt;&gt; print(_dlopen('/venv/lib/python3.4/site-packages/google/assistant/library/libassistant_embedder.so', RTLD_LOCAL))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
OSError: File not found
```
- But, if I change another share object (eg: libportaudio), it could open successfully and return handling number.
```
&gt;&gt;&gt; print(_dlopen('/usr/lib/libportaudio.so.2.0.0', RTLD_LOCAL))
18166401
```

**Comment by Fleker** [comment]
Can you find the file `/venv/lib/python3.4/site-packages/google/assistant/library/libassistant_embedder.so` in a file explorer or is it not there either?

**Comment by harry0890** [comment]
Yeah, I can find the file `/venv/lib/python3.4/site-packages/google/assistant/library/libassistant_embedder.so`

```
/venv/lib/python3.4/site-packages/google/assistant/library/ # ls
LICENSE.third_party       __pycache__               event.py
__init__.py               assistant.py              file_helpers.py
__main__.py               auth_helpers.py           libassistant_embedder.so
```
and the file information:
`libassistant_embedder.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped`

**Comment by hkwan72** [comment]
is there any updated on this issue?
now i'm experiencing the same issue as below;

 # googlesamples-assistant-hotword 
Traceback (most recent call last):
  File "/usr/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/googlesamples/assistant/library/hotword.py", line 136, in main
    with Assistant(credentials, args.device_model_id) as assistant:
  File "/usr/lib/python2.7/site-packages/google/assistant/library/assistant.py", line 90, in __init__
    self._load_lib()
  File "/usr/lib/python2.7/site-packages/google/assistant/library/assistant.py", line 251, in _load_lib
    self._lib = cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python2.7/site-packages/google/assistant/library/libassistant_embedder.so: internal error

# ls /usr/lib/python2.7/site-packages/google/assistant/lib
rary/
LICENSE.third_party       assistant.pyc             file_helpers.pyc
__init__.py               auth_helpers.py           libassistant_embedder.so
__init__.pyc              auth_helpers.pyc          version.py
__main__.py               event.py                  version.pyc
__main__.pyc              event.pyc
assistant.py              file_helpers.py

stat /usr/lib/python2.7/site-packages/google/assistant/l
ibrary/libassistant_embedder.so
  File: /usr/lib/python2.7/site-packages/google/assistant/library/libassistant_embedder.so
  Size: 11504740        Blocks: 22472      IO Block: 4096   regular file
Device: ch/12d  Inode: 8375        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1980-01-06 15:00:21.000000000
Modify: 1980-01-06 15:00:20.000000000
Change: 1980-01-06 15:00:22.000000000

please let me know if  there is a way to fix this matter .
thanks.
