### ISSUE TITLE
pushtotalk.py throws an error when no voice command is given

### ISSUE THREAD

**Issue by spenceco** [googlesamples/assistant-sdk-python#185]
Basically if you press enter while running pushtotalk.py and don't say anything for several seconds, this error gets thrown:

`Traceback (most recent call last):
  File "pushtotalk.py", line 435, in <module>
    main()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pushtotalk.py", line 424, in main
    continue_conversation = assistant.assist()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "pushtotalk.py", line 169, in assist
    self.conversation_stream.stop_playback()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 288, in stop_playback
    self._source.stop()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 221, in stop
    self.flush()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 211, in flush
    self._audio_stream.write(b'\x00' * self._flush_size)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/sounddevice.py", line 1202, in write
    _check(err)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Can't write to an input only stream [PaErrorCode -9974]
`

It seems like as soon as you start speaking, the stream becomes writable. How can I close this stream wihle it is input-only?

**Comment by shivasiddharth** [comment]
Same as #155

**Comment by proppy** [comment]
@spenceco can you give a try to #188

**Comment by spenceco** [comment]
still getting the same error:

Traceback (most recent call last):
  File "pushtotalk.py", line 435, in <module>
    main()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pushtotalk.py", line 424, in main
    continue_conversation = assistant.assist()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "pushtotalk.py", line 169, in assist
    self.conversation_stream.stop_playback()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 288, in stop_playback
    self._source.stop()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 221, in stop
    self.flush()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 211, in flush
    self._audio_stream.write(b'\x00' * self._flush_size)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/sounddevice.py", line 1202, in write
    _check(err)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Can't write to an input only stream [PaErrorCode -9974]

**Comment by spenceco** [comment]
throws this error:

Traceback (most recent call last):
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/grpc/_channel.py", line 187, in consume_request_iterator
    request = next(request_iterator)
  File "pushtotalk.py", line 123, in iter_assist_requests
    for c in self.gen_assist_requests():
  File "pushtotalk.py", line 201, in gen_assist_requests
    for data in self.conversation_stream:
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers_fixed.py", line 313, in <lambda>
    return iter(lambda: self.read(self._iter_size), b'')
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers_fixed.py", line 295, in read
    return self._source.read(size)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/googlesamples/assistant/grpc/audio_helpers_fixed.py", line 189, in read
    buf, overflow = self._audio_stream.read(size)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/sounddevice.py", line 1107, in read
    _check(err)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Stream is stopped [PaErrorCode -9983]
Traceback (most recent call last):
  File "pushtotalk.py", line 435, in <module>
    main()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pushtotalk.py", line 424, in main
    continue_conversation = assistant.assist()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "pushtotalk.py", line 131, in assist
    self.deadline):
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/grpc/_channel.py", line 347, in __next__
    return self._next()
  File "/home/pi/Projects/virtual_envs/spence.codes_venv/lib/python3.6/site-packages/grpc/_channel.py", line 341, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.CANCELLED, Cancelled)>

**Comment by proppy** [comment]
@spenceco can you give it another try, I fixed a typo :)

**Comment by spenceco** [comment]
looks like its fine now! thanks!

**Comment by spenceco** [comment]
actually, while this fixes the aforementioned issue, now it the code seems to hang whenever I actually DO give some voice input. The input is printed out in the terminal, but the code never finishes my audio request and continues execution.

**Comment by PizlaTheDeveloper** [comment]
I have got the same issue with using the #188 
Any solution for this please?

**Comment by 11mail22** [comment]
I have same behavior as @spenceco.
With fresh installed 0.4.4 SDK the error occure like described in the beginning (#185). 
After update audio_helpers.py from #188 (with Typo fixing) hanging without answer (as described by @spenceco three lines above).
Running audio_helpers.py stand alone, also hanging after recording.
So what is the solution?
