### ISSUE TITLE
Error in audio_helpers while setting volume

### ISSUE THREAD

**Issue by PizlaTheDeveloper** [googlesamples/assistant-sdk-python#186]
Hi, I am running google-assistant as grpc service on my RPi-Zero. 
I get this error while trying to set volume using assistant (saying "Set volume up/down")

`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/PiAssistant/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py", line 436, in <module>
    main()
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/PiAssistant/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py", line 425, in main
    continue_conversation = assistant.assist()
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "/home/pi/PiAssistant/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py", line 170, in assist
    self.conversation_stream.stop_playback()
  File "/home/pi/PiAssistant/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 288, in stop_playback
    self._source.stop()
  File "/home/pi/PiAssistant/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 221, in stop
    self.flush()
  File "/home/pi/PiAssistant/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 211, in flush
    self._audio_stream.write(b'\x00' * self._flush_size)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/sounddevice.py", line 1202, in write
    _check(err)
  File "/home/pi/PiAssistant/env/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Can't write to an input only stream [PaErrorCode -9974]
`

Any solution for this please?
Thank you

**Comment by Fleker** [comment]
What happens if you set volume directly "Set volume to ninety percent"?

**Comment by PizlaTheDeveloper** [comment]
The same result :(
flushing - writing the zeroed array to the stream makes the problem

**Comment by PizlaTheDeveloper** [comment]
Probably it is the same issue as #185

**Comment by proppy** [comment]
@PizlaTheDeveloper can you give a try to #188 ?
