### ISSUE TITLE
'Device or resource busy' [ALSA error -16]

### ISSUE THREAD

**Issue by JakeMalis** [googlesamples/assistant-sdk-python#193]
Traceback (most recent call last):
  File "pushtotalk.py", line 437, in <module>
    main()
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pushtotalk.py", line 334, in main
    flush_size=audio_flush_size
  File "/home/pi/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/audio_helpers.py", line 187, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1256, in __init__
    **_remove_self(locals()))
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 772, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2561, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening RawStream: Unanticipated host error [PaErrorCode -9999]: 'Device or resource busy' [ALSA error -16]

**Comment by Fleker** [comment]
> 'Device or resource busy' [ALSA error -16]

Are you running anything else on your Pi at the same time?

**Comment by JakeBMalis** [comment]
I do not. When I set the speaker output to my monitor it works but when I use my mic and speaker HAT I get the error. I have a Seeed ReSpeaker HAT with 2 microphones and a 3.5 mm headphone jack. I know that they can both work at the same time. If I run the command (arecord -f cd -Dhw:1 | aplay -Dhw:1) it will output to my headphones whatever I say.

**Comment by Fleker** [comment]
So you're having an issue with the ReSpeaker 2-Mic hat?

**Comment by JakeBMalis** [comment]
I don't know if it is an issue with the HAT... It works using both the mic and speaker output at the same time, but using it with the assistant integration seems to not allow one card to use both of them.

**Comment by Fleker** [comment]
What is the content of `~/.asoundrc`? Does it have the correct sound card info?

**Comment by JakeBMalis** [comment]
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

**Comment by JakeMalis** [comment]
The issue is gone, thanks for all the help!
