### ISSUE TITLE
Error when trying to send a new request after several minutes of inactivity

### ISSUE THREAD

**Issue by alfongj** [googlesamples/assistant-sdk-python#2]
**Issue**: client throws an error after pressing enter after several minutes of inactivity

**Steps to reproduce**:
1. Run the client
2. Press enter, say something, hear response
3. Wait 5-10 minutes
4. Press enter again. Fails

**Error trace**:
```
Press Enter to send a new request...
INFO:root:Recording audio request.
Traceback (most recent call last):
File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
     "__main__", mod_spec)
File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
     exec(code, run_globals)
File "/home/pi/embedded-assistant-sdk-python/googlesamples/assistant/__main__.py", line 254, in <module>
     main()
File "/home/pi/assistant/env/lib/python3.4/site-packages/click/core.py", line 722, in __call__
     return self.main(*args, **kwargs)
File "/home/pi/assistant/env/lib/python3.4/site-packages/click/core.py", line 697, in main
     rv = self.invoke(ctx)
File "/home/pi/assistant/env/lib/python3.4/site-packages/click/core.py", line 895, in invoke
     return ctx.invoke(self.callback, **ctx.params)
File "/home/pi/assistant/env/lib/python3.4/site-packages/click/core.py", line 535, in invoke
     return callback(*args, **kwargs)
File "/home/pi/embedded-assistant-sdk-python/googlesamples/assistant/__main__.py", line 214, in main
     grpc_deadline):
File "/home/pi/assistant/env/lib/python3.4/site-packages/grpc/_channel.py", line 363, in __next__
     return self._next()
File "/home/pi/assistant/env/lib/python3.4/site-packages/grpc/_channel.py", line 357, in _next
     raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)> 
```

**Comment by proppy** [comment]
Should be fixed with 7da41cfbcd4f5aa0e0e34aa01a1ea1fdfb04b83b, feel free to give it a try
