### ISSUE TITLE
Problem with python -m pip install --upgrade google-assistant-grpc

### ISSUE THREAD

**Issue by ManPython** [googlesamples/assistant-sdk-python#215]
Again problem with **python -m pip install --upgrade google-assistant-grpc** 

C:\>E:\Python36\python -m pip install --upgrade google-assistant-grpc
Collecting google-assistant-grpc
  Using cached google_assistant_grpc-0.1.0-py2.py3-none-any.whl
Collecting grpcio>=1.3.5 (from google-assistant-grpc)
  Using cached grpcio-1.10.0-cp36-cp36m-win32.whl
Collecting googleapis-common-protos>=1.5.2 (from google-assistant-grpc)
  Using cached googleapis-common-protos-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "E:\Python36\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "E:\Python36\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\x\AppData\Local\Temp\pip-build-16zz_d20\googleapis-common-protos\

**Comment by ManPython** [comment]
**Python36\python -m pip install google-assistant-grpc**
Collecting google-assistant-grpc
  Downloading https://files.pythonhosted.org/packages/0c/87/dd76876d4312881a93f8827a8d7d81ed9a13daadf1f53a5fd4eca96d8412/google_assistant_grpc-0.1.0-py2.py3-none-any.whl
Collecting grpcio>=1.3.5 (from google-assistant-grpc)
  Downloading https://files.pythonhosted.org/packages/d2/e6/e5dba9e2d9aa7ac4e08142f92749098e84e2261623af7cba400fa91f60b8/grpcio-1.10.0-cp36-cp36m-win32.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 453kB/s
Collecting googleapis-common-protos>=1.5.2 (from google-assistant-grpc)
  Downloading https://files.pythonhosted.org/packages/00/03/d25bed04ec8d930bcfa488ba81a2ecbf7eb36ae3ffd7e8f5be0d036a89c9/googleapis-common-protos-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "E:\Python36\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "E:\Python36\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "E:\Python36\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\x\AppData\Local\Temp\pip-build-s91ke2be\googleapis-common-protos\

**Comment by Fleker** [comment]
Are you running in a [Python virtual environment](https://docs.python.org/3/library/venv.html)?

**Comment by ManPython** [comment]
@Fleker no, I'm not using env. It's realy "must be"? In my opinion it's not relateed with venv

**Comment by Fleker** [comment]
Using one has always worked for me, although I don't think it's necessarily required.

**Comment by rubimazaki** [comment]
I have the same problem. with googleapis-common-protos-1.5.3 not being installed. 
Note it's a 64 bit python (3.6). Shoud there be any problem with 64 bit python over 32?

**Comment by rubimazaki** [comment]
Solved! just do that:

pip install --upgrade pip and pip install --upgrade setuptools

**Comment by ManPython** [comment]
@rubimazaki thx, this helped me to
