### ISSUE TITLE
sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985] in the grpc sample

### ISSUE THREAD

**Issue by moham96** [googlesamples/assistant-sdk-python#219]
Hi,
This issue is related to the stream fix work that was done by @proppy  in #188.
Testing on the raspberry pi 3 (running under python3)
If I use the master branch (includes the fix) I get the following error:
```
(env3dev) ➜  ~ googlesamples-assistant-pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
Traceback (most recent call last):
  File "/home/pi/env3dev/bin/googlesamples-assistant-pushtotalk", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env3dev/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env3dev/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env3dev/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env3dev/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env3dev/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 347, in main
    flush_size=audio_flush_size
  File "/home/pi/env3dev/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/env3dev/lib/python3.5/site-packages/sounddevice.py", line 1256, in __init__
    **_remove_self(locals()))
  File "/home/pi/env3dev/lib/python3.5/site-packages/sounddevice.py", line 772, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/pi/env3dev/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]
```

While if I don't use these fixes (using the  0.4.4  sable release ) I can run the sample with no errors and i can interact with the assistant but sometimes I get the usual audio errors:

```
(env) ➜  ~ googlesamples-assistant-pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
WARNING:root:SoundDeviceStream read overflow (3200, 6400)
INFO:root:Transcript of user request: "tell".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell me".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell me a".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell me a joke".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell  me a joke".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell me  a joke".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell me a  joke".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "tell me a joke".
INFO:root:Playing assistant response.
INFO:root:End of audio request detected
INFO:root:Transcript of user request: "tell me a joke".
INFO:root:Playing assistant response.
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
INFO:root:Finished playing assistant response.
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:End of audio request detected
INFO:root:Finished playing assistant response.
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:End of audio request detected
INFO:root:Finished playing assistant response.
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:End of audio request detected
INFO:root:Finished playing assistant response.
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-pushtotalk", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 424, in main
    continue_conversation = assistant.assist()
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 169, in assist
    self.conversation_stream.stop_playback()
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 288, in stop_playback
    self._source.stop()
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 221, in stop
    self.flush()
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 211, in flush
    self._audio_stream.write(b'\x00' * self._flush_size)
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 1202, in write
    _check(err)
  File "/home/pi/env/lib/python3.5/site-packages/sounddevice.py", line 2563, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Can't write to an input only stream [PaErrorCode -9974]
```

This error I get only on the raspberry pi, if I run the sample on my laptop I have no problem using the master branch

Thanks.

**Comment by moham96** [comment]
I just discovered that on my laptop if I have a .asoundrc file in my home directory that uses the devices directly I get the same error
`sounddevice.PortAudioError: Error opening RawStream: Device unavailable [PaErrorCode -9985]`

.asoundrc content:
```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
```
while if I change the content of asoundrc file to use pulseaudio the `Device unavailable` goes a way and I can interact with the assistant with no problems
```
pcm.!default {
  type pulse
  fallback "sysdefault"
  hint {
    show on
    description "Default ALSA Output (currently PulseAudio Sound Server)"
  }
}

ctl.!default {
  type pulse
  fallback "sysdefault"
}

```

**Comment by PizlaTheDeveloper** [comment]
You will have to set PulseAudio default devices.
e.g. [(https://askubuntu.com/questions/14077/how-can-i-change-the-default-audio-device-from-command-line)]

or uninstall PulseAudio :)

**Comment by moham96** [comment]
Ok I did more tests on the raspberry pi.
I installed PulseAudio and started it and voila the `Device Unavailable` error is gone and the grpc sample works fine(Although the sound is stuttering, might be related to raspberrypi/linux#994 ?).
I didn't have to change the .asoundrc configuration to get the sample working, only having pulseaudio running in the background solves the problem even if I delete ~/.asoundrc and /etc/asound.conf .
This is not Ideal since I don't like using pulse and it would be better to have the sample working on alsa only system.

**Comment by Whuzz** [comment]
I *think* this has something to do with the changes in pushtotalk.py. 
In main, after : # Configure audio source and sink.
Both audio_source and audio_sink call upon the SoundDeviceStream, causing two in- or output streams to be opened. 

I might be completely mistaken though, since I'm no expert in python (yet). 
I'm trying to fix it by splitting the audio_helper's rawstream into a rawinputstream and a rawoutputstream. So far, I've got it work, with the "minor" flaw of the assistant now sounding like a chipmunk. I saw that problem somewhere, so it should be fixable.

At least no more "Device Unavailable" anymore.

**Comment by moham96** [comment]
@Whuzz can you post your changes So I can try?

**Comment by moham96** [comment]
Strangely enough, I ran the `audio_helpers.py` and was able to record and playback the audio with no "Device Unavailable" error. So what is the problem in the `pushtotalk.py` that is causing the issue! I can't see any difference in `pushtotalk.py` compared to `audio_helpers.py` that might cause the issue.
@Whuzz  can you run the `googlesamples-assistant-audiotest` and see If You have the "Device Unavailable" error?

**Comment by Whuzz** [comment]
My main change is in audio_helpers.py:

```
def __init__(self, sample_rate, sample_width, block_size, flush_size, device_used, channels_used, direction):
        if sample_width == 2:
            audio_format = 'int16'
        else:
            raise Exception('unsupported sample width:', sample_width)
        if direction == 0:
            self._audio_stream = sd.RawInputStream(
                samplerate=sample_rate, dtype=audio_format, channels=1,
                blocksize=int(block_size/2), device=device_used # blocksize is in number of frames.
            )
            self._block_size = block_size
            self._flush_size = flush_size
            self._sample_rate = sample_rate
            self.device_used = device_used
            self.channels_used = channels_used
            
        if direction == 1:
            self._audio_stream = sd.RawOutputStream(
                samplerate=sample_rate, dtype=audio_format, channels=1,
                blocksize=int(block_size/2), device=device_used # blocksize is in number of frames.
            )
            self._block_size = block_size
            self._flush_size = flush_size
            self._sample_rate = sample_rate
            self.device_used = device_used
            self.channels_used = channels_used
```
I set the channels to hardcoded 1 at the moment, but of course you can give them as arguments.
In pushtotalk.py I added some arguments to the audio_source and audio_sink definitions, so that each has its own "direction".

It works, but it seems to crash (hang) at random intervals at the moment, so I'll need to make it more robust.

**Comment by moham96** [comment]
@Whuzz I used your changes only I ditched `device=device_used` and `self.channels_used = channels_used` and It Fixed the problem.
When you said that you get underflow error is it fatal(does the script exits) or does the script runs with no problem? I think this error is not important If the assistant mic and speakers works fine.
@proppy  Can You take a look at @Whuzz fix above ?

**Comment by moham96** [comment]
Maybe It's because of your "difficult" audio setup, try using a single mic, I think you can disable the 7 mics from Alsa and leave only one mic working.

**Comment by Whuzz** [comment]
I need (well... *really* want) to use the 8 mics. In ALSA they are available as a single (beamformed) device, so it should be fine. Works with the assistant SDK library just fine. I'm mainly using the GRPC right now since I believe that might help me solve the bluetooth problem (see other bug report). 

Once it's working, I plan on injecting "silent frames" before each assistant response to prevent audio loss.

**Comment by Starlon87** [comment]
@moham96 I met the same error on Raspberry Pi 3B

"I used your changes only I ditched device=device_used and self.channels_used = channels_used and It Fixed the problem."
Could you told me more details to fix it?

**Comment by proppy** [comment]
@moham96 @Whuzz @Starlon87 can you share mode details about your audio setup? (Which sound card, alsa configuration, pulseaudio or not?)

**Comment by Whuzz** [comment]
Soundcard for output: Standard Raspberry Pi, Jack out. (or bluealsa / Bluez, but for now testing with basic settings)
Sound for input: Matrix Creator 8 mic array

Alsa:
```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}

pcm.mic {
   type softvol
   slave {
     pcm "array"
   }
   control {
     name "MicArray Master"
        card 0
   }
}

pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}

pcm.array {
  type plug
  slave {
    pcm "hw:2,0"
  }
}
```
No pulseaudio.

**Comment by Starlon87** [comment]
1.platform:  Raspberry Pi 3B
2.recorder:  card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
3.speaker:   card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
4.No pulseaudio
5.alsa configuration:

pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,1"
  }
}

6.Description:
run 'googlesamples-assistant-pushtotalk XXX' is OK.
run 'python pushtotalk.py' Failed. (without any changes)

**Comment by Whuzz** [comment]
I think I have narrowed down when/how the pushtotalk "hangs". It *always* seems to happen during "click.pause", so while waiting for the next conversation to start. 
This *even* happens when there has been *NO* conversation before. So this seems to come from the grpc itself. 

This is after I have started pushtotalk (with --verbose, no other options): 

`DEBUG:google.auth.transport.requests:Making request: POST https://accounts.google.com/o/oauth2/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Using device model unity-home-assistant-matrix-creator-main-rwjd85 and device id 9576b686-3a88-11e8-9d84-b827eb0d7e69
Press Enter to send a new request...
INFO:root:Recording audio request.
DEBUG:root:AssistRequest: config {
  audio_in_config {
    encoding: LINEAR16
    sample_rate_hertz: 16000
  }
  audio_out_config {
    encoding: LINEAR16
    sample_rate_hertz: 16000
    volume_percentage: 50
  }
  dialog_state_in {
    language_code: "en-US"
  }
  device_config {
    device_id: "9576b686-3a88-11e8-9d84-b827eb0d7e69"
    device_model_id: "unity-home-assistant-matrix-creator-main-rwjd85"
  }
}
^C
Aborted!
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/local/lib/python3.5/dist-packages/grpc/_common.py", line 135, in join
    super(CleanupThread, self).join(timeout)
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^C
`

**Comment by moham96** [comment]
@proppy OK, I tried it and it works fine, but I'm curious why didn't you go with @Whuzz solution? for me, it looks more elegant, are there any advantages of your solution over @Whuzz  solution?

Thank you for your great work :1st_place_medal:

**Comment by Whuzz** [comment]
Seems to work fine. 

I still suffer from the crashes, but that is unrelated to this issue I think. I'll investigate further and raise a new issue if needed.

**Comment by proppy** [comment]
@moham96 I wanted to minimize the code changes for stability, filed https://github.com/googlesamples/assistant-sdk-python/issues/229 to track improvement we need to do to the audio streaming handling.

@Whuzz can you file a separate issue for the crash you're experiencing and confirm if you're using the `MATRIX Voice` or the `MATRIX Creator` ?
