### ISSUE TITLE
Recording audio request...

### ISSUE THREAD

**Issue by kronflux** [googlesamples/assistant-sdk-python#22]
Alright, so I've got sound both recording and playing back perfectly using both arecord/aplay as well as the googlesamples.assistant.audio_helpers functions.
However, when I run googlesamples.assistant, I hear nothing, and when I press Enter, I get "Recording audio request." and nothing else. I've tried giving requests, even tried yelling into the mic. Absolutely nothing. Just sits there at Recording.

To be clear, I'm using a different device, however the dependencies have all been met. (PineA64) and as I said, audio is recording and playing back perfectly.

any insight on how I might diagnose the issue?

**Comment by proppy** [comment]
What happens if you run the samples with `-v` ?

**Comment by kronflux** [comment]
INFO:ubuntu:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:ubuntu:Recording audio request.
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.p                                                                                        y", line 320, in <module>
    main()
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 722, in __cal                                                                                        l__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 895, in invok                                                                                        e
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 535, in invok                                                                                        e
    return callback(*args, **kwargs)
  File "/home/ubuntu/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.p                                                                                        y", line 313, in main
    continue_conversation = assistant.converse()
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 87, in                                                                                         wrapped_f
    return r.call(f, *args, **kw)
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 235, i                                                                                        n call
    do = self.iter(result=result, exc_info=exc_info)
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 194, i                                                                                        n iter
    return fut.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_resu                                                                                        lt
    raise self._exception
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 238, i                                                                                        n call
    result = fn(*args, **kwargs)
  File "/home/ubuntu/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.p                                                                                        y", line 101, in converse
    self.deadline):
  File "/home/ubuntu/env/lib/python3.4/site-packages/grpc/_channel.py", line 363, in __                                                                                        next__
    return self._next()
  File "/home/ubuntu/env/lib/python3.4/site-packages/grpc/_channel.py", line 357, in _n                                                                                        ext
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.                                                                                        DEADLINE_EXCEEDED, Deadline Exceeded)>
(env) ubuntu@DietPine:~# python -m googlesamples.assistant -v
DEBUG:google.auth.transport.requests:Making request: POST https://accounts.googl                                                                                        e.com/o/oauth2/token
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1)                                                                                        : accounts.google.com
DEBUG:requests.packages.urllib3.connectionpool:https://accounts.google.com:443 "                                                                                        POST /o/oauth2/token HTTP/1.1" 200 None
INFO:ubuntu:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:ubuntu:Recording audio request.
DEBUG:ubuntu:ConverseRequest: config {
  audio_in_config {
    encoding: LINEAR16
    sample_rate_hertz: 16000
  }
  audio_out_config {
    encoding: LINEAR16
    sample_rate_hertz: 16000
    volume_percentage: 50
  }
}

**Comment by kronflux** [comment]
and if I leave it for several minutes(around 5-10?) it spits out this:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.py", line 320, in <module>
    main()
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/env/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.py", line 313, in main
    continue_conversation = assistant.converse()
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 87, in wrapped_f
    return r.call(f, *args, **kw)
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 235, in call
    do = self.iter(result=result, exc_info=exc_info)
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 194, in iter
    return fut.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/home/ubuntu/env/lib/python3.4/site-packages/tenacity/__init__.py", line 238, in call
    result = fn(*args, **kwargs)
  File "/home/ubuntu/env/lib/python3.4/site-packages/googlesamples/assistant/__main__.py", line 101, in converse
    self.deadline):
  File "/home/ubuntu/env/lib/python3.4/site-packages/grpc/_channel.py", line 363, in __next__
    return self._next()
  File "/home/ubuntu/env/lib/python3.4/site-packages/grpc/_channel.py", line 357, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>

and terminates.

**Comment by proppy** [comment]
Yep, it sounds like something might be off with the networking.

Are you able to call other API successfully from that setup?

**Comment by kronflux** [comment]
I haven't really tried a whole lot else yet, this is a fresh install. but network connectivity for other tasks work fine so I really don't know.

**Comment by proppy** [comment]
Were you able to run the `auth_helpers` successfully too?

**Comment by kronflux** [comment]
yep! all setup up to actually running the assistant sample worked perfectly.

**Comment by proppy** [comment]
@kronflux can you share the details of your setup:
- microphone
- speaker
- board revision

I'd like to try reproducing your issue.

**Comment by kronflux** [comment]
Microphone is a cheap ebay USB one which doesn't have a brand name or markings on it
http://www.ebay.ca/itm/USB-Stand-Instrument-Mic-Microphone-for-Tablet-Laptop-Black-Mini-Studio-/182547604720

Speaker is using the analog audio jack, and is of no particular interest(I built it, but it's working for everything, so any old analog speaker should do)

Board is PineA64 A64-DB-V1.1 2G (201-A64DB110-02)

OS is DietPi(debian based)

**Comment by proppy** [comment]
Are you connected to the network thru ethernet?

**Comment by kronflux** [comment]
WiFi (signal strength is excellent[using Google OnHub])

Are there any particular ports that it uses, that I might want to try forwarding?

**Comment by proppy** [comment]
> WiFi (signal strength is excellent[using Google OnHub])

Are you using the Pine64 wifi module https://www.pine64.org/?product=wifi-802-11bgn-bluetooth-4-0-module for that?

> Are there any particular ports that it uses, that I might want to try forwarding?

Traffic should only be long-lived outbound HTTP/2.0 + TLS

**Comment by kronflux** [comment]
Yep! That's the guy. Came with mine :)
