### ISSUE TITLE
pip install error using zsh

### ISSUE THREAD

**Issue by JElgar** [googlesamples/assistant-sdk-python#28]
Im having a few issues, but im probably just being a bit stupid.
This command: python -m pip install --upgrade google-assistant-sdk[samples]
returns: zsh: no matches found: google-assistant-sdk[samples]
and this: python -m pip install --upgrade -e ".[samples]"
returns: Directory '.' is not installable. File 'setup.py' not found.

I therefore just ran: python -m pip install --upgrade google-assistant-sdk 
and now when i run this: python -m googlesamples.assistant.auth_helpers --client-secrets my_path_to_thing
It returns: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/james/env/lib/python3.6/site-packages/googlesamples/assistant/auth_helpers/__init__.py", line 20, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'

Any help would be greatly appreciated
Thank you

**Comment by proppy** [comment]
can you try:
```
 python -m pip install --upgrade 'google-assistant-sdk[samples]'
```
I think zsh might be trying the interpret the `[]` character.

Also make sure you upgraded pip and setuptools using
```
python -m pip install setuptools pip --upgrade
```

**Comment by irvanrahadhian** [comment]
@proppy Thank you for the solution by upgrade pip and setuptools.

**Comment by tshanib** [comment]
I did both, but still showing same result 

Traceback (most recent call last):
  File "c:\users\shani\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shani\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\shani\AppData\Local\Programs\Python\Python36\Scripts\googlesamples-assistant-hotword.exe\__main__.py", line 5, in <module>
  File "c:\users\shani\appdata\local\programs\python\python36\lib\site-packages\googlesamples\assistant\library\hotword.py", line 26, in <module>
    from google.assistant.library import Assistant
ModuleNotFoundError: No module named 'google.assistant.library'


Please help

**Comment by proppy** [comment]
@tshanib in order to run the `hotword` sample you need to `pip install google-assistant-library`
