### ISSUE TITLE
After pushing to talk and hitting enter, i get the error: Exception iterating requests!

### ISSUE THREAD

**Issue by fbjac01** [googlesamples/assistant-sdk-python#280]
I get this with anything I say. 
C:\Users\Felix>googlesamples-assistant-pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Using device model rock-micron-212522-pi-hscshi and device id 3439f614-99d5-11e8-89c9-5800e3e95be6
Press Enter to send a new request...
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "hey Google".
INFO:root:Transcript of user request: "hey Google".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 338, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\grpc\_channel.py", line 180, in consume_request_iterator
    request = next(request_iterator)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python37-32\Scripts\googlesamples-assistant-pushtotalk.exe\__main__.py", line 9, in <module>
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\tenacity\__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\tenacity\__init__.py", line 330, in call
    start_time=start_time)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\tenacity\__init__.py", line 279, in iter
    return fut.result()
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\tenacity\__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 139, in assist
    self.deadline):
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\grpc\_channel.py", line 345, in __next__
    return self._next()
  File "c:\users\felix\appdata\local\programs\python\python37-32\lib\site-packages\grpc\_channel.py", line 328, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>

**Comment by Fleker** [comment]
This looks like an ongoing issue with Windows, as per #246.

**Comment by Zylvian** [comment]
I have the exact same problem, have found zero fixes.

**Comment by Noraccire** [comment]
same problem here , no solution found ?
