### ISSUE TITLE
regarding google/assistant/library/libassistant_embedder.so: internal error

### ISSUE THREAD

**Issue by hkwan72** [googlesamples/assistant-sdk-python#286]
Hi,
when i run google assistant hotword on my device(which is based on MDM9307 arm) , i'm experiencing the  issue as below;

i'm used  below cases and got the same error. 
1)google_assistant_library-1.0.0-py2.py3-none-linux_armv7l.whl
 google_assistant_sdk-0.5.0-py2.py3-none-any.whl

=====  log ===========================================
google_sdk050# googlesamples-assistant-hotword --project_id
xxxxx  --device_model_id xxxxxxxxxxx
Traceback (most recent call last):
  File "/usr/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/googlesamples/assistant/library/hotword.py", line 122, in main
    with Assistant(credentials, device_model_id) as assistant:
  File "/usr/lib/python2.7/site-packages/google/assistant/library/assistant.py", line 90, in __init__
    self._load_lib()
  File "/usr/lib/python2.7/site-packages/google/assistant/library/assistant.py", line 270, in _load_lib
    self._lib = cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python2.7/site-packages/google/assistant/library/libassistant_embedder.so: internal error

2) google_assistant_library-0.1.1-py2.py3-none-linux_armv7l.whl
 google_assistant_sdk-0.4.4-py2.py3-none-any.whl

=====  log ===========================================
Traceback (most recent call last):
File "/usr/bin/googlesamples-assistant-hotword", line 11, in 
sys.exit(main())
File "/usr/lib/python2.7/site-packages/googlesamples/assistant/library/hotword.py", line 136, in main
with Assistant(credentials, args.device_model_id) as assistant:
File "/usr/lib/python2.7/site-packages/google/assistant/library/assistant.py", line 90, in init
self._load_lib()
File "/usr/lib/python2.7/site-packages/google/assistant/library/assistant.py", line 251, in _load_lib
self._lib = cdll.LoadLibrary(lib_path)
File "/usr/lib/python2.7/ctypes/init.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/init.py", line 365, in init
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python2.7/site-packages/google/assistant/library/libassistant_embedder.so: internal error

ls /usr/lib/python2.7/site-packages/google/assistant/lib
rary/
LICENSE.third_party assistant.pyc file_helpers.pyc
init.py auth_helpers.py libassistant_embedder.so
init.pyc auth_helpers.pyc version.py
main.py event.py version.pyc
main.pyc event.pyc
assistant.py file_helpers.py

stat /usr/lib/python2.7/site-packages/google/assistant/l
ibrary/libassistant_embedder.so
File: /usr/lib/python2.7/site-packages/google/assistant/library/libassistant_embedder.so
Size: 11504740 Blocks: 22472 IO Block: 4096 regular file
Device: ch/12d Inode: 8375 Links: 1
Access: (0644/-rw-r--r--) Uid: ( 0/ root) Gid: ( 0/ root)
Access: 1980-01-06 15:00:21.000000000
Modify: 1980-01-06 15:00:20.000000000
Change: 1980-01-06 15:00:22.000000000

based on the log, it seems that the problem is due to that ctypes _dlopen can not open this library "/usr/lib/python2.7/site-packages/google/assistant/library/libassistant_embedder.so"
is there any solution or integration guide to fix this matter?
does python version of google assistant hotword working on arm v7 linux platform?
can we preload the google assistant hotword package on the device that use arm platform without using apt get install or pip tool? 
if possible, please let us know how to get the package and preload them on the device.

thanks.

**Comment by Fleker** [comment]
The Python version should work on armv7, although I haven't tried any board other than the Raspberry Pi so I'm not sure.
