### ISSUE TITLE
Problem on device_type after upgrade google assistant-ibrary

### ISSUE THREAD

**Issue by MauricioRibeiroA** [googlesamples/assistant-sdk-python#296]
Hi all,

I was running the old version of Google AIY on my Raspi 3B+ without problems until now. After I used the command "pip install --upgrade google-assistant-library" I started to receive these message:

"Traceback (most recent call last):
  File "src/assistant_library_demo.py", line 75, in <module>
    main()
  File "src/assistant_library_demo.py", line 69, in main
    with Assistant(credentials) as assistant:
TypeError: __init__() missing 1 required positional argument: 'device_model_id'"

Can someone help me in which file I need to add the device_model_id? I was looking at internet but couldn't find.

Regards,

Mauricio

**Comment by Fleker** [comment]
You should be able to include the flag as a parameter in your command line. [Device registration](https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device) is something that was added at the end of last year.

You run the sample like:

`googlesamples-assistant-hotword --project-id my-dev-project --device-model-id my-model`
