### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by Zylvian** [googlesamples/assistant-sdk-python#304]
Seems to happen whenever it reacts to that I said something.

Here's the traceback:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 192, in consume_request_iterator
    request = next(request_iterator)
  File "/usr/local/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 131, in iter_log_assist_requests
    for c in self.gen_assist_requests():
  File "/usr/local/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 217, in gen_assist_requests
    for data in self.conversation_stream:
RuntimeError: generator raised StopIteration
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 469, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 279, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 139, in assist
    self.deadline):
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
>
`

**Comment by chrjak** [comment]
Hi! Total scrub to this, and in need of help (windows 10). I get the same error, with the same traceback, and i have tried way too many solutions to no avail. I have scoured the web and now i created this account as a desperate scream for help.

**Comment by proppy** [comment]
Looks similar to https://github.com/googlesamples/assistant-sdk-python/issues/246 can you try installing from master?
