### ISSUE TITLE
Google assistant error(security policy) on Respeaker core v2.0

### ISSUE THREAD

**Issue by ParkChur** [googlesamples/assistant-sdk-python#341]
I want to use google assistant on Respekaer core 2.0

I follow this site : http://wiki.seeedstudio.com/Google_Assistant/

but i cant activate google assistant with this error

Help me Plz

------
Traceback (most recent call last):
  File "/usr/local/bin/googlesamples-assistant-respeakerd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in call
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleassistant_respeakerd/assist_with_respeakerd.py", line 402, in main
    pub = system_bus.publish("io.respeaker.respeakerd", dbus_obj)
  File "/usr/local/lib/python2.7/dist-packages/pydbus/publication.py", line 42, in publish
    return Publication(self, bus_name, *objects)
  File "/usr/local/lib/python2.7/dist-packages/pydbus/publication.py", line 35, in init
    self._at_exit(bus.request_name(bus_name, allow_replacement=allow_replacement, replace=replace).__exit__)
  File "/usr/local/lib/python2.7/dist-packages/pydbus/request_name.py", line 29, in request_name
    return NameOwner(self, name, allow_replacement, replace)
  File "/usr/local/lib/python2.7/dist-packages/pydbus/request_name.py", line 8, in init
    res = bus.dbus.RequestName(name, flags)
  File "/usr/local/lib/python2.7/dist-packages/pydbus/proxy_method.py", line 75, in call
    0, timeout_to_glib(timeout), None).unpack()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.33" is not allowed to own the service "io.respeaker.respeakerd" due to security policies in the configuration file (9)

**Comment by Inza** [comment]
Hello, I have run into the exact same issue. Has anybody managed to solve this? Thanks.

**Comment by shivasiddharth** [comment]
This is meant to be posted in Respeaker's forums. What you are using is a Seeedstudio's modified version of the gRPC assistant.
