### ISSUE TITLE
add google-assistant-library deprecation notice

### ISSUE THREAD

**Issue by proppy** [googlesamples/assistant-sdk-python#359]
This repository and the associated artifact on pypi should be updated to match the deprecated state of the google-assistant-library advertised in the documentation at https://developers.google.com/assistant/sdk/release-notes in order to provide clarification to the current developer community and avoid confusion for new developers (see #356)

For example:
- top-level [README](https://github.com/googlesamples/assistant-sdk-python/blob/master/README.md) should mention the deprecation
- a new wheel for `google-assistant-library` should be published on https://pypi.org/project/google-assistant-library/ with `Development Status :: 7 - Inactive
` and a runtime [`DeprecationWarning`](https://docs.python.org/3.7/library/warnings.html)
- `google-assistant-library` [directory](https://github.com/googlesamples/assistant-sdk-python/tree/84995692f35be8e085de8dfa7032039a13ae3fab/google-assistant-library) and [ sample](https://github.com/googlesamples/assistant-sdk-python/tree/84995692f35be8e085de8dfa7032039a13ae3fab/google-assistant-sdk/googlesamples/assistant/library) can be removed

**Comment by proppy** [comment]
(Finally) verified that the deprecation notice is visible when installing the new wheel (`1.1.0`) on Raspberry Pi Zero w/ the latest `2019-09-26-raspbian-buster-lite.img`

But get the following stacktrace when starting the demo
```
#0  strlen () at ../sysdeps/arm/armv6/strlen.S:26
#1  0xb530ed04 in ?? () from /home/pi/env/lib/python3.7/site-packages/google/assistant/library/libassistant_embedder.so
#2  0xb530a3b4 in assistant_new () from /home/pi/env/lib/python3.7/site-packages/google/assistant/library/libassistant_embedder.so
#3  0xb6645cc0 in ffi_call_VFP () from /usr/lib/arm-linux-gnueabihf/libffi.so.6
#4  0xb66466cc in ffi_call () from /usr/lib/arm-linux-gnueabihf/libffi.so.6
#5  0xb666da38 in _ctypes_callproc () from /usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m-arm-linux-gnueabihf.so
#6  0xb666e4ec in ?? () from /usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m-arm-linux-gnueabihf.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

This seems equivalent to what was reported for `1.0.1` in https://github.com/googlesamples/assistant-sdk-python/issues/355

**Comment by proppy** [comment]
The following patch seems to fix the segfault:
```
--- env/lib/python3.7/site-packages/google/assistant/library/assistant.py~      2019-12-18 08:07:00.039021501 +0000
+++ env/lib/python3.7/site-packages/google/assistant/library/assistant.py       2019-12-18 08:31:35.365685657 +0000
@@ -100,8 +100,7 @@
         self._inst = c_void_p(
             self._lib.assistant_new(
                 self._event_callback,
-                None,
-                device_model_id.encode('ASCII')))
+                device_model_id.encode('ASCII'), None))

         self._credentials_refresher = CredentialsRefresher(
             credentials, self._set_credentials)
@@ -278,7 +277,7 @@

         # void* assistant_new(EventCallback listener, const char*
         # device_model_id);
-        self._lib.assistant_new.argtypes = [EVENT_CALLBACK, c_char_p]
+        self._lib.assistant_new.argtypes = [EVENT_CALLBACK, c_char_p, c_char_p]
         self._lib.assistant_new.restype = c_void_p

         # void assistant_free(void* instance);
```

**Comment by proppy** [comment]
Published https://github.com/googlesamples/assistant-sdk-python/releases/tag/0.6.0 with the deprecation notice (and the segfault fix).
