### ISSUE TITLE
trying to run `python3 -m pushtotalk.py` on Raspbery pi

### ISSUE THREAD

**Issue by COKELERDO** [googlesamples/assistant-sdk-python#371]
trying to run `python3 -m pushtotalk.py`

getting `Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/ZeroExample/pushtotalk.py", line 29, in <module>
    import google.auth.transport.grpc
  File "/home/pi/env/lib/python3.7/site-packages/google/auth/transport/grpc.py", line 32, in <module>
    class AuthMetadataPlugin(grpc.AuthMetadataPlugin):
AttributeError: module 'grpc' has no attribute 'AuthMetadataPlugin'`

any idea?

**Comment by Fleker** [comment]
Which version of gRPC is being used?

**Comment by COKELERDO** [comment]
I believe I have 1.12.0

`Requirement already satisfied: grpcio in /home/pi/env/lib/python3.7/site-packages (1.24.1)
Requirement already satisfied: six>=1.5.2 in /home/pi/env/lib/python3.7/site-packages (from grpcio) (1.12.0)`

**Comment by Fleker** [comment]
Looking at the message, I think your version of gRPC is 1.24.1
