### ISSUE TITLE
Cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by hkarakose** [googlesamples/assistant-sdk-python#390]
I am trying to run id_card_detection_image.py program. I receive following error. How can I fix this?

```
WARNING: Logging before flag parsing goes to stderr.
W0225 22:12:39.109291 4549164480 __init__.py:329] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "/Users/halil/Projects/id-card-detector/id_card_detection_image.py", line 15, in <module>
    from utils import label_map_util
  File "/Users/halil/Projects/id-card-detector/utils/label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'
```

**Comment by Fleker** [comment]
That error is unrelated to this project. It looks related to Tensorflow.
