### ISSUE TITLE
AssertionError after running googlesamples-assistant-pushtotalk ...

### ISSUE THREAD

**Issue by Badbird5907** [googlesamples/assistant-sdk-python#398]
I am using a raspberry pi 4B and after following the instructions at https://developers.google.com/assistant/sdk/guides/service/python/embed/run-sample I ran this line: `googlesamples-assistant-pushtotalk --project-id my-dev-project --device-model-id my-model` with the project ID and the device ID and I get the following error:
`Traceback (most recent call last):
  File "/home/pi/.local/bin/googlesamples-assistant-pushtotalk", line 6, in <module>
    from googlesamples.assistant.grpc.pushtotalk import main
  File "/home/pi/.local/lib/python2.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 40, in <module>
    from . import (
  File "/home/pi/.local/lib/python2.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 25, in <module>
    import sounddevice as sd
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 2777, in <module>
    _initialize()
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 2745, in _initialize
    _check(_lib.Pa_Initialize(), 'Error initializing PortAudio')
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 2651, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: <exception str() failed>
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 2762, in _exit_handler
    assert _initialized >= 0
AssertionError
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 2762, in _exit_handler
    assert _initialized >= 0
AssertionError`

**Comment by Badbird-5907** [comment]
before that error, i got this error:
`INFO:root:Connecting to embeddedassistant.googleapis.com
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "/home/pi/.local/bin/googlesamples-assistant-pushtotalk", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 351, in main
    flush_size=audio_flush_size
  File "/home/pi/.local/lib/python2.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 190, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 1345, in __init__
    **_remove_self(locals()))
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 861, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/pi/.local/lib/python2.7/site-packages/sounddevice.py", line 2653, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]`
but changing my .asoundrc file to `sym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}`
got me the error in the first post.

**Comment by mijazm** [comment]
Have you tried use these commands to test whether your audio works?
```
# Play a test sound
speaker-test -t wav

# Record and play back some audio using ALSA command-line tools
arecord --format=S16_LE --duration=5 --rate=16000 --file-type=raw out.raw
aplay --format=S16_LE --rate=16000 --file-type=raw out.raw
```
