### ISSUE TITLE
raise PortAudioError; what's this?

### ISSUE THREAD

**Issue by ghost** [googlesamples/assistant-sdk-python#404]
I'm trying to use Google Assistant on PC by following this link[https://www.lifewire.com/google-assistant-on-windows-4628292], but is causes error on my computer...
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts>python -m googlesamples.assistant.grpc.pushtotalk --device-model-id "GA4W" --project-id astute-veld-277614
INFO:root:Connecting to embeddedassistant.googleapis.com
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 469, in <module>
    main()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\googlesamples\assistant\grpc\pushtotalk.py", line 347, in main
    audio_device or audio_helpers.SoundDeviceStream(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\googlesamples\assistant\grpc\audio_helpers.py", line 188, in __init__
    self._audio_stream = sd.RawStream(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sounddevice.py", line 1344, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='buffer',
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sounddevice.py", line 760, in __init__
    iparameters, idtype, isize, isamplerate = _get_stream_parameters(
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sounddevice.py", line 2571, in _get_stream_parameters
    info = query_devices(device)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sounddevice.py", line 569, in query_devices
    raise PortAudioError('Error querying device {0}'.format(device))
### **_sounddevice.PortAudioError: Error querying device -1_**
I think error is causing by PortAudioError, what should I do?

**Comment by Fleker** [comment]
Seems like there's an error querying your device. You can debug with `py -m googlesamples.assistant.grpc.audio_helpers`.
