### ISSUE TITLE
termux android 9 

### ISSUE THREAD

**Issue by deva-kataxi** [googlesamples/assistant-sdk-python#412]
i installed termux in android 9 and i'm trying to run wifiphisher but pop out this error  message

note!
i dont have root access

root@localhost:~# wifiphisher

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-09-30 00:11
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyric/lib/libnl.py", line 187, in nl_socket_alloc
    s = socket.socket(socket.AF_NETLINK,socket.SOCK_RAW,nlh.NETLINK_GENERIC)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 2277, in _nlstub_
    nlsock = nl.nl_socket_alloc(timeout=2)
  File "/usr/lib/python3/dist-packages/pyric/lib/libnl.py", line 193, in nl_socket_alloc
    raise error(e.errno,e.strerror)
libnl.error: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 709, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 400, in start
    self.opmode.initialize(args)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 797, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 2281, in _nlstub_
    raise pyric.error(e.errno, pyric.strerror(e.errno))
pyric.error: [Errno 13] Permission denied

**Comment by beckmx** [comment]
I don't think this is the right repo for your question
