### ISSUE TITLE
When i install the auto_backup module and when i run Manually this error is occure plzz any one help

### ISSUE THREAD

**Issue by phpdevelper0101** [googlesamples/assistant-sdk-python#416]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/extra-addons/auto_backup/models/db_backup.py", line 152, in schedule_backup
    os.makedirs(rec.folder)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/flectra'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/flectra/addons/web/controllers/main.py", line 1094, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/flectra/addons/web/controllers/main.py", line 1082, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/addons/base/ir/ir_cron.py", line 76, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "/usr/lib/python3/dist-packages/flectra/addons/base/ir/ir_actions.py", line 555, in run
    res = func(action, eval_context=eval_context)
  File "/usr/lib/python3/dist-packages/flectra/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/usr/lib/python3/dist-packages/flectra/addons/base/ir/ir_actions.py", line 431, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/lib/python3/dist-packages/flectra/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/usr/lib/python3/dist-packages/flectra/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/flectra/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/extra-addons/auto_backup/models/db_backup.py", line 152, in schedule_backup
    os.makedirs(rec.folder)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
ValueError: <class 'PermissionError'>: "13
Permission denied" while evaluating
'model.schedule_backup()'

**Comment by Fleker** [comment]
This is the wrong location to file an issue of your sort. You are having file system permission issues.
