### ISSUE TITLE
googlesamples-assistant-hotword run issue

### ISSUE THREAD

**Issue by Whyzanet** [googlesamples/assistant-sdk-python#458]
I have followed the guide at

https://developers.google.com/assistant/sdk/guides/service/python

to install assistant on my Raspberry Pi buster device

After performing the credential step, registering the device, saving the credential file to the default location without issues, I then find as per the guide step 6 samples I can run  the following

googlesamples-assistant-pushtotalk

successfully and interact with the assistant.
All good. 

But when I try to run 

 googlesamples-assistant-hotword

which is not covered in the guide, I get the following error

(env) pi@piai:~ $ googlesamples-assistant-hotword
/home/pi/env/lib/python3.7/site-packages/urllib3/util/selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import namedtuple, Mapping
/home/pi/env/lib/python3.7/site-packages/urllib3/_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, MutableMapping
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 8, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.7/site-packages/googlesamples/assistant/library/hotword.py", line 66, in main
    with Assistant(credentials) as assistant:
TypeError: __init__() missing 1 required positional argument: 'device_model_id'

Which indicates an issue with device_model_id

If I run 

googlesamples-assistant-hotword --help

after installing

python -m pip install --upgrade google.assistant.library

I get 

googlesamples-assistant-hotword --help
/home/pi/env/lib/python3.7/site-packages/urllib3/util/selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import namedtuple, Mapping
/home/pi/env/lib/python3.7/site-packages/urllib3/_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, MutableMapping
usage: googlesamples-assistant-hotword [-h]
                                       [--credentials OAUTH2_CREDENTIALS_FILE]

optional arguments:
  -h, --help            show this help message and exit
  --credentials OAUTH2_CREDENTIALS_FILE
                        Path to store and read OAuth2 credentials

Which indicates the only argument is the credentials file which it is already locating from its default location as per googlesamples-assistant-pushtotalk.

As such I have tried specifying 

--project-id my-dev-project --device-model-id my-model

without success. 

googlesamples-assistant-hotword --project_id XXX --device_model_id YYY
usage: googlesamples-assistant-hotword [-h]
                                       [--credentials OAUTH2_CREDENTIALS_FILE]
googlesamples-assistant-hotword: error: unrecognized arguments: --project_id XXX --device_model_id YYY

Any ideas on how I can get googlesamples-assistant-hotword to be happy and run for me ?

**Comment by Whyzanet** [comment]
The solution is 

google-assistant-demo --device-model-id XXX
